### ISSUE TITLE
Parsing error? "invalid type array length"

### ISSUE THREAD

**Issue by martinhschei** [danwild/leaflet-geotiff-2#15]
I have a TIFF that resulted in the error in the title. The TIFF have been inspected with QGIS and verified that it is ok and i have used the same TIFF with georaster-layer-for-leaflet without problems.

I try to load the TIFF like this:

```
  const renderer = L.LeafletGeotiff.rgb();
    const options = {
      rBand: 0,
      gBand: 1,
      bBand: 2,
      alphaBand: 0,
      transpValue: 0,
      renderer: renderer,
    };
    var layer = L.leafletGeotiff("C:\\TEMP\\bands.tiff.0.tif", options).addTo(this.map);
```

The metadata is logged to console on line 183 but the rendering fails with several errors like this:

"RangeError: Invalid typed array length: -4695"

There are many errors like this in the console with different numbers, -12401, -20107, -27813, etc.

Could it be that my TIFF is created with some unsupported parameters?

Any suggestions?

**Comment by danwild** [comment]
Hi @martinhschei,

Due to my own priorities I have mostly focused on improving the plotty renderer, and haven't made changes to the original rgb renderer (from which this project was forked).

Tips:
- check if the issue occurs with the [original plugin](https://github.com/christian-werner/leaflet-geotiff), so we know if it is a regression
- supply some example data so others can help troubleshoot

**Comment by martinhschei** [comment]
Ok - thanks!
